[package]
name = "unifed-tff"
version = "0.0.0"
keywords = ["federated learning", "machine learning"]
description = "tff is TensorFlow Federated for short, it's based on TensorFlow."
language = "python"


install_script = """
if { conda env list | grep 'colink-protocol-unifed-tff'; } >/dev/null 2>&1; then
    conda env remove -n colink-protocol-unifed-tff
fi
conda create -n colink-protocol-unifed-tff python=3.9.16 -y
conda activate colink-protocol-unifed-tff
pip install --upgrade pip
pip install tensorflow-federated==0.42.0
pip install tensorflow-probability==0.15.0
pip install flbenchmark
pip install nest_asyncio
pip install pillow
pip install tensorflow-addons==0.19.0
pip install scikit-learn
pip install pytest
pip install -e .
"""

entrypoint = """
conda activate colink-protocol-unifed-tff
unifed-tff
"""
